<?php

namespace ContainerQMhYZxb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HaMdnPKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.haMdnPK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\ArticleAdminController::list' => ['privates', '.service_locator.KL2mrpd.App\\Controller\\Admin\\ArticleAdminController::list()', 'getArticleAdminControllerlistService', true],
            'App\\Controller\\Admin\\ArticleAdminController::create' => ['privates', '.service_locator.KL2mrpd.App\\Controller\\Admin\\ArticleAdminController::create()', 'getArticleAdminControllercreateService', true],
            'App\\Controller\\Admin\\ArticleAdminController::edit' => ['privates', '.service_locator.aUekZYp.App\\Controller\\Admin\\ArticleAdminController::edit()', 'getArticleAdminControllereditService', true],
            'App\\Controller\\Admin\\ArticleAdminController::delete' => ['privates', '.service_locator.aUekZYp.App\\Controller\\Admin\\ArticleAdminController::delete()', 'getArticleAdminControllerdeleteService', true],
            'App\\Controller\\Admin\\CommentAdminController::list' => ['privates', '.service_locator.KL2mrpd.App\\Controller\\Admin\\CommentAdminController::list()', 'getCommentAdminControllerlistService', true],
            'App\\Controller\\Admin\\CommentAdminController::delete' => ['privates', '.service_locator.9b.wWNZ.App\\Controller\\Admin\\CommentAdminController::delete()', 'getCommentAdminControllerdeleteService', true],
            'App\\Controller\\ArticleController::list' => ['privates', '.service_locator.rr3BW8T.App\\Controller\\ArticleController::list()', 'getArticleControllerlistService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.OhhwhSf.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.KL2mrpd.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.51hHbbT.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\ArticleAdminController:list' => ['privates', '.service_locator.KL2mrpd.App\\Controller\\Admin\\ArticleAdminController::list()', 'getArticleAdminControllerlistService', true],
            'App\\Controller\\Admin\\ArticleAdminController:create' => ['privates', '.service_locator.KL2mrpd.App\\Controller\\Admin\\ArticleAdminController::create()', 'getArticleAdminControllercreateService', true],
            'App\\Controller\\Admin\\ArticleAdminController:edit' => ['privates', '.service_locator.aUekZYp.App\\Controller\\Admin\\ArticleAdminController::edit()', 'getArticleAdminControllereditService', true],
            'App\\Controller\\Admin\\ArticleAdminController:delete' => ['privates', '.service_locator.aUekZYp.App\\Controller\\Admin\\ArticleAdminController::delete()', 'getArticleAdminControllerdeleteService', true],
            'App\\Controller\\Admin\\CommentAdminController:list' => ['privates', '.service_locator.KL2mrpd.App\\Controller\\Admin\\CommentAdminController::list()', 'getCommentAdminControllerlistService', true],
            'App\\Controller\\Admin\\CommentAdminController:delete' => ['privates', '.service_locator.9b.wWNZ.App\\Controller\\Admin\\CommentAdminController::delete()', 'getCommentAdminControllerdeleteService', true],
            'App\\Controller\\ArticleController:list' => ['privates', '.service_locator.rr3BW8T.App\\Controller\\ArticleController::list()', 'getArticleControllerlistService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.OhhwhSf.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.KL2mrpd.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.51hHbbT.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\ArticleAdminController::list' => '?',
            'App\\Controller\\Admin\\ArticleAdminController::create' => '?',
            'App\\Controller\\Admin\\ArticleAdminController::edit' => '?',
            'App\\Controller\\Admin\\ArticleAdminController::delete' => '?',
            'App\\Controller\\Admin\\CommentAdminController::list' => '?',
            'App\\Controller\\Admin\\CommentAdminController::delete' => '?',
            'App\\Controller\\ArticleController::list' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\ArticleAdminController:list' => '?',
            'App\\Controller\\Admin\\ArticleAdminController:create' => '?',
            'App\\Controller\\Admin\\ArticleAdminController:edit' => '?',
            'App\\Controller\\Admin\\ArticleAdminController:delete' => '?',
            'App\\Controller\\Admin\\CommentAdminController:list' => '?',
            'App\\Controller\\Admin\\CommentAdminController:delete' => '?',
            'App\\Controller\\ArticleController:list' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.haMdnPK'])) {
            return $container->privates['.service_locator.haMdnPK'];
        }

        return $container->privates['.service_locator.haMdnPK'] = $instance;
    }
}
