<?php

namespace ContainerQMhYZxb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AUekZYpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aUekZYp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aUekZYp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.aUekZYp.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.aUekZYp": it needs an instance of "App\\Entity\\Article" but this type has been excluded because it\'s a Doctrine entity.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'article' => 'App\\Entity\\Article',
            'doctrine' => '?',
        ]);
    }
}
