<?php

namespace ContainerQMhYZxb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OhhwhSf.App\Controller\ArticleController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.OhhwhSf.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.OhhwhSf": it needs an instance of "App\\Entity\\Article" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'commentManager' => ['privates', 'App\\Service\\CommentManager', 'getCommentManagerService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'em' => '?',
            'commentManager' => 'App\\Service\\CommentManager',
        ]))->withContext('App\\Controller\\ArticleController::show()', $container);

        if (isset($container->privates['.service_locator.OhhwhSf.App\\Controller\\ArticleController::show()'])) {
            return $container->privates['.service_locator.OhhwhSf.App\\Controller\\ArticleController::show()'];
        }

        return $container->privates['.service_locator.OhhwhSf.App\\Controller\\ArticleController::show()'] = $instance;
    }
}
