<?php

namespace ContainerQMhYZxb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CommentManager' shared autowired service.
     *
     * @return \App\Service\CommentManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CommentManager.php';

        return $container->privates['App\\Service\\CommentManager'] = new \App\Service\CommentManager(($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')));
    }
}
