<?php

namespace ContainerQMhYZxb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateArticleCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateArticleCommand' shared autowired service.
     *
     * @return \App\Command\CreateArticleCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateArticleCommand.php';

        $container->privates['App\\Command\\CreateArticleCommand'] = $instance = new \App\Command\CreateArticleCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-article');
        $instance->setDescription('Crée un article de test.');

        return $instance;
    }
}
