<?php

namespace ContainerWpcNb4o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentAdminControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KL2mrpd.App\Controller\Admin\CommentAdminController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KL2mrpd.App\\Controller\\Admin\\CommentAdminController::list()'] = ($container->privates['.service_locator.KL2mrpd'] ?? $container->load('get_ServiceLocator_KL2mrpdService'))->withContext('App\\Controller\\Admin\\CommentAdminController::list()', $container);
    }
}
