<?php

namespace ContainerWpcNb4o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentAdminControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9b.wWNZ.App\Controller\Admin\CommentAdminController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9b.wWNZ.App\\Controller\\Admin\\CommentAdminController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator.9b.wWNZ.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.9b.wWNZ": it needs an instance of "App\\Entity\\Comment" but this type has been excluded because it\'s a Doctrine entity.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\Admin\\CommentAdminController::delete()', $container);
    }
}
