<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLs532XK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLs532XK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLs532XK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLs532XK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLs532XK\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ls532XK',
    'container.build_id' => '3fd4b28d',
    'container.build_time' => 1770592051,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLs532XK');
