<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpcNb4o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpcNb4o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWpcNb4o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWpcNb4o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWpcNb4o\App_KernelDevDebugContainer([
    'container.build_hash' => 'WpcNb4o',
    'container.build_id' => '9879557f',
    'container.build_time' => 1770404779,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWpcNb4o');
